#### general settings
name: csrnet
use_tb_logger: true
model: sr
distortion: sr
scale: 1
gpu_ids: [0]

#### datasets
datasets:
  train:
    name: MIT_fivek
    mode: LQGT_enhance
    dataroot_GT: ../datasets/expert_C_train
    dataroot_LQ: ../datasets/raw_input_train

    use_shuffle: true
    n_workers: 16
    batch_size: 1
    color: RGB

  val:
    name: MIT_fivek_500
    mode: LQGT_enhance
    dataroot_GT: ../datasets/expert_C_test
    dataroot_LQ: ../datasets/raw_input_test

#### network structures
network_G:
  which_model_G: CSRNet
  in_nc: 3
  out_nc: 3
  base_nf: 64
  cond_nf: 32


#### path
path:
  root: 
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  lr_scheme: MultiStepLR # MultiStepLR | CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 600000
  warmup_iter: -1  # no warm up
  lr_scheme: MultiStepLR
  lr_steps: [100000, 200000, 300000, 400000, 500000]
  lr_gamma: 0.5

  pixel_criterion: l1
  pixel_weight: 1.0

  manual_seed: 10
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
